# Generated by Django 4.1 on 2022-08-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_gender_alter_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='auth',
            fields=[
                ('authID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/'),
        ),
    ]
